apiVersion: v1
kind: Namespace
metadata:
  name: research-tenant-default
  labels:
    tenant: default
---
apiVersion: v1
kind: Namespace
metadata:
  name: research-tenant-example
  labels:
    tenant: example

